#!/bin/bash

BASEDIR=`pwd`
SRC_DIR="$BASEDIR/src-subjects"
INPUT="$SRC_DIR/Sudoku"
OUTPUT="$SRC_DIR/Out_Sudoku"
#FEATURES="BASE STATES UNDO"
TEST_CLASS="src-subjects/Out_Sudoku/src-tests/sudoku/main/tests/TestAll.java"
TEST_PATH="sudoku.main.tests.TestAll"

echo "...running preprocessor"
echo "${INPUT} ${OUTPUT} BASE STATES UNDO"

cd src/antenna/
ant compile_v3
cd ../..
#java -jar antenna.jar ${INPUT} ${OUTPUT} BASE STATES UNDO SOLVER GENERATOR EXTENDED_SUDOKU
java -cp src/antenna/bin:src/antenna/lib/antlr-3.0.1.jar:src/antenna/lib/commons-io-1.0.jar main.PreProcessMain ${INPUT} ${OUTPUT} BASE STATES UNDO SOLVER GENERATOR EXTENDED_SUDOKU

echo "...compiling output"
JAVA_FILES=`find ${OUTPUT} -name "*.java"`

BINDIR="${OUTPUT}/bin"
rm -r "${BINDIR}"
mkdir -p ${BINDIR}
javac -nowarn -d ${BINDIR} -cp ${BINDIR} ${JAVA_FILES}
 
#echo "...compiling test"
#javac -d ${BINDIR} -sourcepath src -cp ${BINDIR} ${TEST_CLASS}

echo "...running test"
java -cp ${BINDIR} ${TEST_PATH} 2 > ${OUTPUT}/log_test2.txt

 
